random_seed = 42

[dataset]
# path = "../../data/feature_upd_labels.json"
path = "../../data/dataset.csv"
test_size = 0.2
eval_size = 0.1
max_len = 256
batch_size = 32
num_labels = 3

[model]
name = "cointegrated/rubert-tiny2"
dropout_rate = 0.1
n_epochs = 12
learning_rate = 3e-5
weight_decay = 1e-6
device = "gpu"
